site_name: mBake Guide   

nav:
   - Home: index.md

   - Setup S3 and webdrive mount: s3_n_webdrive_mount.md
   - Mount S3 to linux box via goofys and CA: ca.md
   - Learn Templating/Pug: pug_static_data.md
   - Spectre SCSS Theme Framework and SCSS: spectre_n_scss.md
   - Dynamic databinding: dynamic_data_binding.md
   - Generate a serverless CRUD webapp: crud.md
   - Simple CRUD example app and ViewModel+Bind: model.md
   - Design: design.md
   - Blog: blog.md

   - Resources: res.md
   - About: about.md

theme: readthedocs
docs_dir: src
site_dir: ../docs