site_name: MetaBake&trade; Guide   

nav:
   - Home/About: index.md productivity for progammers, compreshsive - any webapp app, stack
   - HTML/Pug and dat.yaml: pug.md grunt/gulp
   - Watcher: watcher.pug
   
   - SCSS|CSS: scss.md
   - TypeScript|.js: ts.md
   - Website example: web.md
   - SEO/Social SEO: SEO.md 
   - Itemize/Blog example: itemize.md nav optional (CMS)
 
   - Dynamic data/C.R.U.D. example app, 'ViewModel': crud.md Table, Forms, FireStore|DreamFactory and Validation, Auth
   - Review: review.md
 
   - Bonus - MetaCAKE plugins/components for designers: metaCake.md

   - Advanced Level: advanced.md CMS, AMP, Reusable Components, SPA router, Shared Cloud IDE
   - Resources: res.md

theme: readthedocs
docs_dir: src
site_dir: ../docs