site_name: mBake Guide   

nav:
   - Home: index.md

   - Create linux machine, install Caddy with webDAV and mount folder from linux machine to your PC via Mountain Duck: s3_n_webdrive_mount.md
   - Mount linux box folder to another linux box using CodeAnywhere editor: ca.md
   - Learn Templating/Pug: pug_static_data.md
   - Spectre SCSS Theme Framework and SCSS: spectre_n_scss.md
   - Dynamic databinding: dynamic_data_binding.md
   - Generate a serverless CRUD webapp: crud.md
   - Simple CRUD example app and ViewModel+Bind: model.md
   - Design: design.md
   - Blog: blog.md

   - Resources: res.md
   - About: about.md

theme: readthedocs
docs_dir: src
site_dir: ../docs