site_name: MetaBake&trade; Guide   

nav:
   - Home/About: index.md
   - HTML/Pug and dat.yaml: pug.md
   - SCSS|CSS: css.md
   - TypeScript|.js and Services: ts.md

   - Website and .loading .js libs example: webs.md

   - Dynamic data/CRUD example/'ViewModel': crud.md Table, Forms, FireStore|DreamFactory and Validation, Auth
   - SEO/Social SEO: SEO.md 
   - Blog/Itemize example: itemize.md (CMS)
 
   - Review: review.md

   - Next Steps: next.md CMS, AMP, Reusable Components, SPA router, Shared Cloud IDE
   - Bonus - MetaCAKE plugins/components for designers: metaCake.md
   - Resources: res.md

theme: readthedocs
docs_dir: src
site_dir: ../docs